on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - run: echo "BYE"
      - uses: bagbyte/use-private-action@v0.0.2
        with:
          private-action: Sp4Rx/gh-action@v1
          private-action-token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
      # - uses: Sp4Rx/gh-action@v1
      #   with:
      #     who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
      # - run: echo "${{ secrets.GH_ACTION_SSH_KEY_BASE64 }}" | base64 --decode > ssh_key
      #   shell: bash
      # - run: chmod 400 ssh_key
      #   shell: bash
      # - run: git clone git@github.com:Sp4Rx/gh-action.git --config core.sshCommand="ssh -i ssh_key"
      #   shell: bash
      # - run: ls

