on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/checkout@v3
      #   with:
      #     repository: Sp4Rx/gh-action@v1
      #     token: ${{ secrets.GH_KEY }}
      - id: foo
        uses: Sp4Rx/gh-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
